language: ruby
rvm:
  - 2.5

install:
  - gem install jekyll
  - gem install pygments.rb

script:
  - cd doc/zh
  - jekyll build

after_script:
  - cd _site
  - git init
  - git config user.name ${GH_UN}
  - git config user.email ${GH_EMAIL}
  - git add -A
  - git commit -am "$(date "+%Y-%m-%d %H:%M:%S")"
  - git push "https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git" master:${GH_BRANCH} -f

env:
  global:
    - GH_UN=jiangzhonglian
    - GH_EMAIL=jiang-s@163.com
    - GH_USER=apachecn
    - GH_REPO=spark-doc-zh
    - GH_BRANCH=gh-pages
    - SKIP_API=1
